//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define IDS_TITLECAPTION                1
#define IDS_FILEVERSION                 2
#define IDS_APPCOPYRIGHT                3
#define IDS_REGISTRYKEY                 4
#define IDS_STRING5                     5
#define IDC_HANDCURSOR                  100
#define IDI_MAINICON                    101
#define IDI_MAIN                        101
#define IDD_MAIN                        102
#define IDD_NETLOGO                     103
#define IDI_TAB_ADVANCED                103
#define IDI_TAB_CPUS                    104
#define IDI_TAB_GENERAL                 106
#define IDI_TAB_SECURITY                108
#define IDB_TREE_SERVER                 109
#define IDB_TREE_SITESTARTED            110
#define IDB_TREE_SITESTOPPED            111
#define IDB_TREE_CONFIG_ADVANCED        112
#define IDB_TREE_CONFIG_FILTERS         114
#define IDB_TREE_CONFIG_SCRIPTING       115
#define IDI_SMCPU                       115
#define IDI_SMALL_CPU                   115
#define IDB_TREE_CONFIG_PROPPAGE        116
#define IDB_BITMAP1                     118
#define IDB_TREE_CONFIG_WEBSITES        118
#define IDI_DISABLED                    119
#define IDI_ICON2                       120
#define IDI_ENABLED                     120
#define IDB_TREE_CONFIG_CACHE           121
#define IDB_TREE_CONFIG_CGIFOLDERS      122
#define IDB_TREE_CONFIG_CUSTOMFILTERS   128
#define IDB_TREE_CONFIG_DEFAULTPAGES    129
#define IDB_TREE_CONFIG_EXTENSIONFILTERS 130
#define IDB_TREE_CONFIG_IPFILTERS       131
#define IDB_TREE_CONFIG_MIMETYPES       132
#define IDB_TREE_CONFIG_SSIFILES        136
#define IDB_TREE_CONFIG_URLFILTERS      137
#define IDB_TREE_CONFIG_VIRTUALROOTS    138
#define IDB_TREE_CONFIG_COMPRESSION     139
#define IDB_BITMAP3                     140
#define IDB_TREE_CONFIG_SCRIPTINGENGINES 140
#define IDR_MENU1                       141
#define IDR_MAINMENU                    141
#define IDD_DIALOG1                     142
#define IDD_LISTCONFIG                  142
#define IDD_CONFIG_DEFAULTPAGES_ITEM    144
#define IDR_MENU2                       145
#define IDD_CONFIG_GENERICLIST          147
#define IDB_TREE_CONFIG_ERRORPAGES      147
#define IDD_CONFIG_CGIFOLDERS_ITEM      148
#define IDB_TREE_CONFIG_AUTH            148
#define IDB_TREE_CONFIG_AUTHENTICATION  148
#define IDD_CONFIG_URLFILTERS_ITEM      149
#define IDB_TREE_CONFIG_REALMS          149
#define IDD_CONFIG_EXTENSIONFILTERS_ITEM 150
#define IDD_CONFIG_IPFILTERS_ITEM       151
#define IDB_BITMAP2                     151
#define IDB_TREE_CONFIG_SETTINGS        151
#define IDD_CONFIG_SSIFILES_ITEM        152
#define IDB_BITMAP4                     152
#define IDB_TREE_CONFIG_SITE            152
#define IDD_CONFIG_CUSTOMFILTERS_ITEM   153
#define IDI_ICON1                       153
#define IDI_KEYS                        153
#define IDD_CONFIG_MIMETYPES_ITEM       154
#define IDB_TREE_CONFIG_SOCKETPOOLS     154
#define IDD_CONFIG_VIRTUALROOTS_ITEM    155
#define IDB_TREE_CONFIG_POOLACTIVE      155
#define IDD_CONFIG_SCRIPTINGENGINES_ITEM 156
#define IDB_BITMAP6                     156
#define IDB_TREE_CONFIG_POOLINACTIVE    156
#define IDD_CONFIG_COMPRESSIBLEFILES_ITEM 157
#define IDD_CONFIG_COMPRESSIBLEFILESLIST 158
#define IDR_WORKING                     158
#define IDD_CONFIG_SETTINGSLIST         159
#define IDD_CONFIG_ADV                  159
#define IDD_CONFIG_ADVANCED             159
#define IDD_CONFIG_WEBSITES_ITEM        160
#define IDD_CONFIG_ERRORPAGES_ITEM      161
#define IDD_CONFIG_ERRORPAGESLIST       162
#define IDD_CONNECT                     163
#define IDD_CONFIG_MIMETYPES_ITEM1      164
#define IDD_CONFIG_SERVER_USERS         164
#define IDD_TAB_SERVER_SETTINGS_USER    164
#define IDD_CONFIG_GENERICLIST1         165
#define IDD_TAB_SERVER_SETTINGS         165
#define IDD_TAB_PROCESSORS              166
#define IDD_TAB_SERVER_PROCESSORS       166
#define IDD_TAB_ADMINS                  184
#define IDD_TAB_SERVER_SETTINGS_USERS   184
#define IDD_TAB_GENERAL                 185
#define IDD_TAB_SERVER_GENERAL          185
#define IDD_TAB_ADVANCED                190
#define IDD_TAB_SERVER_ADVANCED         190
#define IDD_CONFIG_IPFILTERS_ITEM1      191
#define IDD_CONFIG_LISTENIPS_ITEM       191
#define IDD_TAB_CONFIG_SOCKETPOOL_BASIC 192
#define IDD_CONFIG_LISTENIPS_ITEM1      193
#define IDD_CONFIG_HOSTHEADERS_ITEM     193
#define IDD_TAB_CONFIG_SOCKETPOOL_ADVANCED 194
#define IDD_TAB_CONFIG_SOCKETPOOL_IPS   195
#define IDI_TAB_ADMINS                  196
#define IDD_TAB_CONFIG_SOCKETPOOL       196
#define IDD_COMMAND_WAIT                197
#define IDD_CONFIG_ADVANCED_SECURITY    198
#define IDD_CONFIG_ADVANCED_ADVANCED    200
#define IDC_TEXTBOX                     1000
#define IDC_NETLINK                     1000
#define IDC_OK                          1001
#define IDC_CPUDESCR                    1001
#define IDC_CANCEL                      1002
#define IDC_STATICTEXT                  1003
#define IDC_IMPORT                      1003
#define IDC_HELPBUTTON                  1003
#define IDC_ABOUTICON                   1004
#define IDC_EXPORT                      1004
#define IDC_APPNAME                     1005
#define IDC_APPVERSION                  1006
#define IDC_APPCOPYRIGHT                1007
#define IDC_OKBUTTON                    1008
#define IDC_BUILDTIMEDATE               1009
#define IDC_GLLOGO                      1010
#define IDC_SITES                       1011
#define IDC_LIST1                       1012
#define IDC_DETAIL                      1012
#define IDC_LIST                        1012
#define IDC_CHECK1                      1013
#define IDC_ENABLED                     1013
#define IDC_DIRINDEXING                 1013
#define IDC_FORCESOCKETREUSE            1013
#define IDC_OPTIMIZEFORTHROUGHPUT       1013
#define IDC_CONFIGTITLE                 1014
#define IDC_DIRINDEXING2                1014
#define IDC_PREVENTIMAGELEACHING        1014
#define IDC_ADD                         1015
#define IDC_SCANREQUEST                 1015
#define IDC_CONFIGTITLE3                1015
#define IDC_TEMPFILELOCATION            1015
#define IDC_BUTTON2                     1016
#define IDC_DELETE                      1016
#define IDC_BLURB                       1016
#define IDC_SCANQUERY                   1016
#define IDC_ADD_IP                      1016
#define IDC_EDITSOCKETPOOLS             1016
#define IDC_CONFIGTITLE6                1016
#define IDC_DIRINDEXING3                1016
#define IDC_EDIT                        1017
#define IDC_CONFIGTITLE4                1017
#define IDC_MOVEUP                      1018
#define IDC_CPUS                        1018
#define IDC_DELETE_IP                   1018
#define IDC_CONFIGTITLE5                1018
#define IDC_DELETE3                     1019
#define IDC_MOVEDOWN                    1019
#define IDC_ENABLEGRIDLINES             1019
#define IDC_PRODUCTTEXT                 1019
#define IDC_ADD_HOST                    1019
#define IDC_NAME                        1020
#define IDC_CONFIGTITLE2                1020
#define IDC_ENABLEFULLROWSELECT         1020
#define IDC_VERSIONTEXT                 1020
#define IDC_EDIT2                       1021
#define IDC_DESCR                       1021
#define IDC_CHECK2                      1021
#define IDC_USEGLOBAL                   1021
#define IDC_ENABLEDRAGDROP              1021
#define IDC_OSTEXT                      1021
#define IDX_FORCESOCKETREUSE            1021
#define IDC_SEQUENCE                    1022
#define IDC_NAME2                       1022
#define IDC_PORT                        1022
#define IDC_EDIT3                       1022
#define IDC_PASSWORD                    1022
#define IDC_SHOWGRIDICONS               1022
#define IDC_MEMORYTEXT                  1022
#define IDC_RETURNDESC                  1022
#define IDC_EXTENSION                   1023
#define IDC_KEEPSELVISIBLEWHILESORTING  1023
#define IDC_PROCESORSTEXT               1023
#define IDC_DELETE_IP2                  1023
#define IDC_DELETE_HOST                 1023
#define IDC_PORT2                       1023
#define IDC_IPADDRESS                   1024
#define IDC_ALWAYSINBACKGROUND          1024
#define IDC_BUILDDATETEXT               1024
#define IDC_PORT3                       1024
#define IDC_FILENAME                    1025
#define IDC_SORTDIRECTION               1025
#define IDC_BUTTON1                     1026
#define IDC_BROWSE                      1026
#define IDC_WARNABOUTNOENCRYPTION       1026
#define IDC_MIMETYPE                    1027
#define IDC_BUTTON3                     1027
#define IDC_SORTITEM                    1027
#define IDC_ROOT                        1028
#define IDC_PATH                        1029
#define IDC_EXECUTABLE                  1030
#define IDC_NTUSERNAME                  1030
#define IDC_PARAMETERS                  1031
#define IDC_NTDOMAIN                    1031
#define IDC_COMPRESSLEVEL               1032
#define IDC_NTPASSWORD                  1032
#define IDC_CHECK3                      1033
#define IDC_COMPRESSDYNAMIC             1033
#define IDC_NTAUTHENABLED               1033
#define IDC_USESUCCESSCODE              1033
#define IDC_MINFILESIZE                 1034
#define IDC_MAXFILESIZE                 1035
#define IDC_CACHEPATH                   1036
#define IDC_MAXCONNECTIONS              1036
#define IDC_SCRIPTTIMEOUT               1037
#define IDC_CACHESIZE                   1039
#define IDC_KEEPALIVETIMEOUT            1039
#define IDC_MEMORYLEVEL                 1040
#define IDC_AUTOSTART                   1040
#define IDC_BUFFERSIZE                  1041
#define IDC_INITBUFFERSIZE              1041
#define IDC_CACHELOGFILE                1042
#define IDC_MAXBUFFERSIZE               1042
#define IDC_BUFFERSIZE2                 1043
#define IDC_MAXRECEIVESIZE              1043
#define IDC_FILEBUFFERSIZE              1043
#define IDC_LOGPATH                     1045
#define IDC_EDIT7                       1046
#define IDC_ADMINEMAIL                  1046
#define IDC_GRAPH                       1047
#define IDC_CODE                        1048
#define IDC_FILE                        1049
#define IDC_EDIT1                       1050
#define IDC_DEFAULTFILE                 1050
#define IDC_HOST                        1050
#define IDC_HOSTNAME                    1050
#define IDC_SUCCESSCODE                 1050
#define IDC_CODE2                       1050
#define IDC_RETURNCODE                  1050
#define IDC_TOPFRAME                    1056
#define IDC_USERNAME                    1057
#define IDC_ALLOWREMOTEMGMT             1057
#define IDC_SERVICESTATUS               1058
#define IDC_IPLIST                      1059
#define IDC_EDIT_IP                     1060
#define IDC_LISTENALLIPS                1061
#define IDC_COMBO1                      1062
#define IDC_HOSTLIST                    1062
#define IDC_EDIT_HOST                   1063
#define IDC_SOCKETPOOLS                 1064
#define IDC_TAB1                        1065
#define IDC_TABCONTROL                  1065
#define IDC_WORKING                     1066
#define IDC_ANIMATE2                    1070
#define IDC_HEADER                      1071
#define IDC_BODYTEXT                    1071
#define IDC_HEADER2                     1072
#define IDC_FOOTER                      1072
#define IDC_PASSWORDLEVEL               1078
#define IDC_TEMPFILELOCATION_CMD        1078
#define IDC_SECUREPASSES_SPIN           1085
#define IDC_SECUREPASSES                1086
#define IDC_USEPREALLOCATION            1087
#define IDC_DRAGDROPCOPYINSTEADOFMOVE   1088
#define IDC_THREADBOOST                 3000
#define IDC_PROCESSBOOST                4000
#define ID_FILE_EXIT                    40001
#define ID_HELP_ABOUT                   40002
#define ID_HELP_PRE                     40003
#define ID_SERVICE_RESTART              40007
#define ID_FILE_CONNECTTO               40008
#define ID_FILE_DISC                    40009
#define ID_SETTINGS_SERVERSETTINGS      40010
#define ID_SETTINGS_WEBSITESETTINGS     40011
#define ID_SETTINGS_ADD                 40014
#define ID_SETTINGS_ADDREMOVE_WEBSITES  40015
#define ID_SERVER_RESTARTSERVER         40016
#define ID_SERVER_RESTARTWEBSITES       40017
#define ID_HELP_                        40018
#define ID_HELP_CONTENTS                40019
#define ID_SERVER_PERSISTSETTINGS       40020

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         40021
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
